//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ilkyar.Contracts.Entities.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Donation : ModelBase
    {
        public long Id { get; set; }
        public long DonatorId { get; set; }
        public int DonationTypeId { get; set; }
        public string DonationInfo { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual DonationType DonationType { get; set; }
        public virtual Donator Donator { get; set; }
    }
}
