//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ilkyar.Contracts.Entities.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class NGOInvitation : ModelBase
    {
        public long Id { get; set; }
        public long RequirementListId { get; set; }
        public int NumberOfStudent { get; set; }
        public int StatusId { get; set; }
        public long SchoolmasterId { get; set; }
    
        public virtual Schoolmaster Schoolmaster { get; set; }
        public virtual UploadRequirementList UploadRequirementList { get; set; }
    }
}
