//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ilkyar.Contracts.Entities.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectDetail : ModelBase
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProjectDetail()
        {
            this.ProjectActivity = new HashSet<ProjectActivity>();
            this.ProjectDetailActivity = new HashSet<ProjectDetailActivity>();
            this.ProjectDetailActivitySchedule = new HashSet<ProjectDetailActivitySchedule>();
            this.ProjectDetailParticipant = new HashSet<ProjectDetailParticipant>();
            this.ProjectDetailVote = new HashSet<ProjectDetailVote>();
            this.RequirementProjectDetail = new HashSet<RequirementProjectDetail>();
            this.Transportation = new HashSet<Transportation>();
            this.VolunteerVote = new HashSet<VolunteerVote>();
        }
    
        public long Id { get; set; }
        public long ProjectId { get; set; }
        public Nullable<int> CityId { get; set; }
        public Nullable<int> TownId { get; set; }
        public int SchoolTypeId { get; set; }
        public string School { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public string ProjectInfo { get; set; }
        public int NumberOfPeople { get; set; }
        public string Inn { get; set; }
        public int StatusId { get; set; }
    
        public virtual City City { get; set; }
        public virtual Project Project { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectActivity> ProjectActivity { get; set; }
        public virtual SchoolType SchoolType { get; set; }
        public virtual Town Town { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectDetailActivity> ProjectDetailActivity { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectDetailActivitySchedule> ProjectDetailActivitySchedule { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectDetailParticipant> ProjectDetailParticipant { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectDetailVote> ProjectDetailVote { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RequirementProjectDetail> RequirementProjectDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transportation> Transportation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VolunteerVote> VolunteerVote { get; set; }
    }
}
