//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ilkyar.Contracts.Entities.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectDetailActivitySchedule : ModelBase
    {
        public long Id { get; set; }
        public long ProjectId { get; set; }
        public long ProjectDetailId { get; set; }
        public long ProjectDetailActivityId { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
    
        public virtual Project Project { get; set; }
        public virtual ProjectDetail ProjectDetail { get; set; }
        public virtual ProjectDetailActivity ProjectDetailActivity { get; set; }
    }
}
