//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ilkyar.Contracts.Entities.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectDetailActivity : ModelBase
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProjectDetailActivity()
        {
            this.ProjectDetailActivitySchedule = new HashSet<ProjectDetailActivitySchedule>();
        }
    
        public long Id { get; set; }
        public int ActivityId { get; set; }
        public long ProjectId { get; set; }
        public long ProjectDetailId { get; set; }
        public long VolunteerId { get; set; }
        public int StatusId { get; set; }
    
        public virtual Activity Activity { get; set; }
        public virtual Project Project { get; set; }
        public virtual ProjectDetail ProjectDetail { get; set; }
        public virtual Volunteer Volunteer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectDetailActivitySchedule> ProjectDetailActivitySchedule { get; set; }
    }
}
