//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ilkyar.Contracts.Entities.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectActivity : ModelBase
    {
        public long Id { get; set; }
        public long ProjectId { get; set; }
        public long ProjectDetailId { get; set; }
        public int ActivityId { get; set; }
    
        public virtual Activity Activity { get; set; }
        public virtual Project Project { get; set; }
        public virtual ProjectDetail ProjectDetail { get; set; }
    }
}
