//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ilkyar.Contracts.Entities.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectDetailVote : ModelBase
    {
        public long Id { get; set; }
        public long ProjectId { get; set; }
        public long ProjectDetailId { get; set; }
        public long UserId { get; set; }
        public int SurveyProjectDetailQuestionId { get; set; }
        public short Vote { get; set; }
    
        public virtual Project Project { get; set; }
        public virtual ProjectDetail ProjectDetail { get; set; }
        public virtual SurveyProjectDetailQuestion SurveyProjectDetailQuestion { get; set; }
        public virtual User User { get; set; }
    }
}
