//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ilkyar.Contracts.Entities.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Report : ModelBase
    {
        public long Id { get; set; }
        public long YonDerId { get; set; }
        public long ScholarshipHolderId { get; set; }
        public string Subject { get; set; }
        public System.DateTime ReportDate { get; set; }
        public string ReportText { get; set; }
    
        public virtual ScholarshipHolder ScholarshipHolder { get; set; }
        public virtual YonDer YonDer { get; set; }
    }
}
