//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ilkyar.Contracts.Entities.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScholarshipHolder : ModelBase
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ScholarshipHolder()
        {
            this.Report = new HashSet<Report>();
            this.Sibling = new HashSet<Sibling>();
        }
    
        public long Id { get; set; }
        public long UserId { get; set; }
        public long DonatorId { get; set; }
        public long YonDerId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public System.DateTime BirthDate { get; set; }
        public string PhoneNumber { get; set; }
        public System.DateTime ScholarshipStartDate { get; set; }
        public Nullable<System.DateTime> ScholarshipEndDate { get; set; }
        public double ScholarshipAmount { get; set; }
        public string IbanNo { get; set; }
        public string EducationLevel { get; set; }
        public string School { get; set; }
        public string Class { get; set; }
        public double CumGPA { get; set; }
        public string StudentDocument { get; set; }
        public string Transcript { get; set; }
        public string HealthConditionInfo { get; set; }
        public double MonthlyIncome { get; set; }
        public string MotherName { get; set; }
        public bool IsMotherWorking { get; set; }
        public int MotherOccupationId { get; set; }
        public string FatherName { get; set; }
        public bool IsFatherWorking { get; set; }
        public int FatherOccupationId { get; set; }
        public int NumberOfSiblings { get; set; }
    
        public virtual Donator Donator { get; set; }
        public virtual Occupation Occupation { get; set; }
        public virtual Occupation Occupation1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Report> Report { get; set; }
        public virtual User User { get; set; }
        public virtual YonDer YonDer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sibling> Sibling { get; set; }
    }
}
