//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ilkyar.Contracts.Entities.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Schoolmaster : ModelBase
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Schoolmaster()
        {
            this.NGOInvitation = new HashSet<NGOInvitation>();
        }
    
        public long Id { get; set; }
        public long UserId { get; set; }
        public Nullable<int> CityId { get; set; }
        public Nullable<int> TownId { get; set; }
        public string School { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public System.DateTime BirthDate { get; set; }
        public string PhoneNumber { get; set; }
    
        public virtual City City { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NGOInvitation> NGOInvitation { get; set; }
        public virtual Town Town { get; set; }
        public virtual User User { get; set; }
    }
}
