//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ilkyar.Contracts.Entities.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScholarshipCommittee : ModelBase
    {
        public long Id { get; set; }
        public long UserId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public System.DateTime BirthDate { get; set; }
        public string Title { get; set; }
        public string PhoneNumber { get; set; }
        public System.DateTime DutyStartDate { get; set; }
        public Nullable<System.DateTime> DutyEndDate { get; set; }
    
        public virtual User User { get; set; }
    }
}
