//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ilkyar.Contracts.Entities.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sibling : ModelBase
    {
        public long Id { get; set; }
        public long ScholarshipHolderId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public int OccupationId { get; set; }
        public double MonthlyIncome { get; set; }
        public bool isLivingTogether { get; set; }
        public bool isWorking { get; set; }
    
        public virtual Occupation Occupation { get; set; }
        public virtual ScholarshipHolder ScholarshipHolder { get; set; }
    }
}
