//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ilkyar.Contracts.Entities.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transportation : ModelBase
    {
        public long Id { get; set; }
        public long ProjectDetailId { get; set; }
        public Nullable<int> TransportationTypeId { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<int> NumberOfPeople { get; set; }
        public string Departure { get; set; }
        public string Comeback { get; set; }
        public string DepartureFirm { get; set; }
        public string ComebackFirm { get; set; }
        public Nullable<int> ComebackTransportationTypeId { get; set; }
        public Nullable<int> ComebackNumberOfPeople { get; set; }
    
        public virtual ProjectDetail ProjectDetail { get; set; }
        public virtual TransportationType TransportationType { get; set; }
        public virtual TransportationType TransportationType1 { get; set; }
    }
}
