//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ilkyar.Contracts.Entities.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class UploadRequirementList : ModelBase
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UploadRequirementList()
        {
            this.NGOInvitation = new HashSet<NGOInvitation>();
        }
    
        public long Id { get; set; }
        public string Name { get; set; }
        public System.DateTime UploadDate { get; set; }
        public byte[] AttachedFile { get; set; }
        public int FileSize { get; set; }
        public string ContentType { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NGOInvitation> NGOInvitation { get; set; }
    }
}
