//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ilkyar.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using Ilkyar.Contracts.Entities.EF;
    
    public partial class IlkyarEntities : DbContext
    {
        public IlkyarEntities()
            : base("name=IlkyarEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Activity> Activity { get; set; }
        public virtual DbSet<Badge> Badge { get; set; }
        public virtual DbSet<BadgeProjectManager> BadgeProjectManager { get; set; }
        public virtual DbSet<BadgeVolunteer> BadgeVolunteer { get; set; }
        public virtual DbSet<Branch> Branch { get; set; }
        public virtual DbSet<City> City { get; set; }
        public virtual DbSet<Conversation> Conversation { get; set; }
        public virtual DbSet<Department> Department { get; set; }
        public virtual DbSet<Donation> Donation { get; set; }
        public virtual DbSet<DonationRecord> DonationRecord { get; set; }
        public virtual DbSet<DonationType> DonationType { get; set; }
        public virtual DbSet<Donator> Donator { get; set; }
        public virtual DbSet<HostSchoolTeacher> HostSchoolTeacher { get; set; }
        public virtual DbSet<InterestVolunteer> InterestVolunteer { get; set; }
        public virtual DbSet<NgoHead> NgoHead { get; set; }
        public virtual DbSet<NGOInvitation> NGOInvitation { get; set; }
        public virtual DbSet<Occupation> Occupation { get; set; }
        public virtual DbSet<Project> Project { get; set; }
        public virtual DbSet<ProjectActivity> ProjectActivity { get; set; }
        public virtual DbSet<ProjectDetail> ProjectDetail { get; set; }
        public virtual DbSet<ProjectDetailActivity> ProjectDetailActivity { get; set; }
        public virtual DbSet<ProjectDetailActivitySchedule> ProjectDetailActivitySchedule { get; set; }
        public virtual DbSet<ProjectDetailParticipant> ProjectDetailParticipant { get; set; }
        public virtual DbSet<ProjectDetailVote> ProjectDetailVote { get; set; }
        public virtual DbSet<ProjectManager> ProjectManager { get; set; }
        public virtual DbSet<ProjectType> ProjectType { get; set; }
        public virtual DbSet<Region> Region { get; set; }
        public virtual DbSet<Report> Report { get; set; }
        public virtual DbSet<RequirementProjectDetail> RequirementProjectDetail { get; set; }
        public virtual DbSet<ScholarshipCommittee> ScholarshipCommittee { get; set; }
        public virtual DbSet<ScholarshipHolder> ScholarshipHolder { get; set; }
        public virtual DbSet<Schoolmaster> Schoolmaster { get; set; }
        public virtual DbSet<SchoolType> SchoolType { get; set; }
        public virtual DbSet<Sibling> Sibling { get; set; }
        public virtual DbSet<Student> Student { get; set; }
        public virtual DbSet<SurveyProjectDetailQuestion> SurveyProjectDetailQuestion { get; set; }
        public virtual DbSet<Town> Town { get; set; }
        public virtual DbSet<Transportation> Transportation { get; set; }
        public virtual DbSet<TransportationType> TransportationType { get; set; }
        public virtual DbSet<University> University { get; set; }
        public virtual DbSet<UploadRequirementList> UploadRequirementList { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<UserType> UserType { get; set; }
        public virtual DbSet<Volunteer> Volunteer { get; set; }
        public virtual DbSet<VolunteerVote> VolunteerVote { get; set; }
        public virtual DbSet<YonDer> YonDer { get; set; }
    }
}
